# -*- coding: utf-8 -*-
"""PyPIX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdZX9S20swiv5VCRnjRY6TCOHFHu4GFe
"""

!pip install qrcode

import qrcode

def gerar_qr_code_pix(valor, destinatario):
  # Gere a chave PIX usando o valor e o nome ou razão social do destinatário
  chave_pix = "VALOR=" + str(valor) + "&DESTINATARIO=" + destinatario
  
  # Crie o QR code a partir da chave PIX
  qr = qrcode.QRCode(
      version=1,
      error_correction=qrcode.constants.ERROR_CORRECT_L,
      box_size=10,
      border=4,
  )
  qr.add_data(chave_pix) # Adicione os dados da chave Pix ao QR Code
  qr.make(fit=True) # Gere o QR Code
  
  # Crie uma imagem a partir do QR Code
  img = qr.make_image(fill_color="black", back_color="white")
  
  # Salve o QR Code em um arquivo de imagem
  img.save("pix.png")
  
  # Imprima o QR Code na tela
  img.show()

# Leia o valor e o destinatário do teclado
valor = input("Insira o valor da transação: ")
destinatario = input("Insira o nome ou razão social do destinatário: ")

# Converta o valor para um número e chame a função com os inputs lidos
gerar_qr_code_pix(float(valor), destinatario)